# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('sport', models.CharField(default='', max_length=30)),
                ('description', models.TextField(default='')),
                ('coach', models.CharField(default='', max_length=50)),
                ('win', models.IntegerField(default=0)),
                ('games', models.IntegerField(default=0)),
                ('logo', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
