# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bets', '0003_auto_20161220_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
