# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 19:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bets', '0004_bet_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='user_bet',
            field=models.ManyToManyField(related_name='users', through='Bets.Bet', to=settings.AUTH_USER_MODEL),
        ),
    ]
